" configuration generated by NIX
set nocompatible

set packpath^=/nix/store/il3i5mb07ryikccwabg0x5rnsl662z4g-vim-pack-dir
set runtimepath^=/nix/store/il3i5mb07ryikccwabg0x5rnsl662z4g-vim-pack-dir

set ignorecase
set mouse=a
set number
set relativenumber
set shiftwidth=2
set tabstop=2

set syntax=true
set clipboard+=unnamedplus
set nowrap
set noswapfile
set splitbelow splitright
" sanskrit binds
inoremap <C-k>.l ḷ
inoremap <C-k>.r ṛ
inoremap <C-k>.m ṃ
inoremap <C-k>.n ṇ
inoremap <C-k>.s ṣ
inoremap <C-k>.t ṭ
inoremap <C-k>.d ḍ
inoremap <C-k>.h ḥ

inoremap <C-k>.L Ḷ
inoremap <C-k>.R Ṛ
inoremap <C-k>.M Ṃ
inoremap <C-k>.N Ṇ
inoremap <C-k>.S Ṣ
inoremap <C-k>.T Ṭ
inoremap <C-k>.D Ḍ
inoremap <C-k>.H Ḥ

