" configuration generated by NIX
set nocompatible

set packpath^=/nix/store/vxlqd1f41wz7p37jiy8wfgqpzzanzdbb-vim-pack-dir
set runtimepath^=/nix/store/vxlqd1f41wz7p37jiy8wfgqpzzanzdbb-vim-pack-dir

set ignorecase
set mouse=a
set number
set relativenumber
set shiftwidth=2
set tabstop=2

set syntax=true
set clipboard+=unnamedplus
set nowrap
set noswapfile
set splitbelow splitright

"set directory tree view
let g:netrw_liststyle= 3
" sanskrit binds
inoremap <C-k>.l ḷ
inoremap <C-k>.r ṛ
inoremap <C-k>.m ṃ
inoremap <C-k>.n ṇ
inoremap <C-k>.s ṣ
inoremap <C-k>.t ṭ
inoremap <C-k>.d ḍ
inoremap <C-k>.h ḥ

inoremap <C-k>.L Ḷ
inoremap <C-k>.R Ṛ
inoremap <C-k>.M Ṃ
inoremap <C-k>.N Ṇ
inoremap <C-k>.S Ṣ
inoremap <C-k>.T Ṭ
inoremap <C-k>.D Ḍ
inoremap <C-k>.H Ḥ
let g:lsp_diagnostics_enabled = 0
let g:lsp_use_native_client = 1

function! s:on_lsp_buffer_enabled() abort
  setlocal omnifunc=lsp#complete
  nmap <buffer> gd <plug>(lsp-definition)
  nmap <buffer> gr <plug>(lsp-references)
  nmap <buffer> K <plug>(lsp-hover)
endfunction

augroup lsp_install
  au!
  " call s:on_lsp_buffer_enabled only for languages that has the server registered.
  autocmd User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
augroup END

