" configuration generated by NIX
set nocompatible

set packpath^=/nix/store/b4zwn8c2x762z5wpkw5dnl1amzv8p8qj-vim-pack-dir
set runtimepath^=/nix/store/b4zwn8c2x762z5wpkw5dnl1amzv8p8qj-vim-pack-dir



set guifont=Inconsolata:h14

set termguicolors
colorscheme base16-stylix
unlet g:colors_name

let g:stylix_colors = {
  \ 'base00': '#131513',
  \ 'base01': '#242924',
  \ 'base02': '#5e6e5e',
  \ 'base03': '#687d68',
  \ 'base04': '#809980',
  \ 'base05': '#8ca68c',
  \ 'base06': '#cfe8cf',
  \ 'base07': '#f4fbf4',
  \ 'base08': '#e6193c',
  \ 'base09': '#87711d',
  \ 'base0A': '#98981b',
  \ 'base0B': '#29a329',
  \ 'base0C': '#1999b3',
  \ 'base0D': '#3d62f5',
  \ 'base0E': '#ad2bee',
  \ 'base0F': '#e619c3',
\ }

" case sensitive searches if capital present
set ignorecase
" mouse on
set mouse=a
" current line number
set number
" line distance
set relativenumber
" number column size
set numberwidth=2

" spaces instead of tab
set expandtab
" indent size
set shiftwidth=2
" backspace indent size
set softtabstop=2
" tab char size
set tabstop=2

" system copy/paste
set clipboard+=unnamedplus
" themed syntax highlighting
set syntax=on
" don't highlight searches
set nohlsearch
" disable linewrap
set nowrap
" keep folder clean
set noswapfile
" window split preference
set splitbelow splitright
" disable auto comment next line
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o
" autocomplete settings
set wildmode=longest,list,full
" display invisible characters | see BINDS
set listchars=tab:>-,space:·,nbsp:␣,trail:•,eol:$,precedes:«,extends:»

" transparent background
highlight Normal guibg=NONE
highlight NonText  guibg=NONE
highlight Normal ctermbg=none
highlight NonText ctermbg=none
"BINDS
nnoremap <space> <Nop>
let mapleader=" "
" toggle invisible characters
nnoremap <silent> <leader>s :setlocal list!<cr>
"SANSKRIT BINDS
inoremap <C-k>.l ḷ
inoremap <C-k>.r ṛ
inoremap <C-k>.m ṃ
inoremap <C-k>.n ṇ
inoremap <C-k>.s ṣ
inoremap <C-k>.t ṭ
inoremap <C-k>.d ḍ
inoremap <C-k>.h ḥ

inoremap <C-k>.L Ḷ
inoremap <C-k>.R Ṛ
inoremap <C-k>.M Ṃ
inoremap <C-k>.N Ṇ
inoremap <C-k>.S Ṣ
inoremap <C-k>.T Ṭ
inoremap <C-k>.D Ḍ
inoremap <C-k>.H Ḥ
"WINDOW
"" resize with ctrl-arrowkey
nnoremap <silent> <C-left> :vertical resize -3<CR>
nnoremap <silent> <C-right> :vertical resize +3<CR>
nnoremap <silent> <C-up> :resize -3<CR>
nnoremap <silent> <C-down> :resize +3<CR>
"LSP
let g:lsp_diagnostics_enabled = 0
let g:lsp_use_native_client = 1

function! s:on_lsp_buffer_enabled() abort
  setlocal omnifunc=lsp#complete
  nmap <buffer> gd <plug>(lsp-definition)
  nmap <buffer> gr <plug>(lsp-references)
  nmap <buffer> K <plug>(lsp-hover)
endfunction

augroup lsp_install
  au!
  " call s:on_lsp_buffer_enabled only for languages that has the server registered.
  autocmd User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
augroup END
"FILE TREE
"" thanks:
""" https://shapeshed.com/vim-netrw/
""" https://vonheikemen.github.io/devlog/tools/using-netrw-vim-builtin-file-explorer/
"" set directory tree view
let g:netrw_liststyle= 3
"" hide banner
let g:netrw_banner= 0
"" open in prev window
let g:netrw_browse_split= 4
"" default size
let g:netrw_winsize=-25
"" open vert
let g:netrw_altv= 1
" fix opening faraway files
let g:netrw_keepdir = 0

" open on launch (don't `vim .`)
augroup ProjectDrawer
  autocmd!
  autocmd VimEnter * :Lexplore
augroup END

" bind open/close toggle
nnoremap <silent> <leader>a :Lexplore<cr>

